### PR TITLE
Feature/add3.2.0

### PR DESCRIPTION
**Pull request by danstreeter**
Added the Dockerfiles for the sonar-scanner 3.2.0 (latest at current time). 

Could you perform the required updates for the docker hub to pick up on these tags?

### CODE REVIEW

**Comment by newtmitch** [comment]
Hey Dan - thanks for the contribution. I'm working on updating these in Docker Hub. I would like to change the maintainer back to my contact into just to keep things consistent, though. Any issue with that?

**Comment by newtmitch** [comment]
Ignore the last comment, I think I'll just merge into my repo and add another commit to update the maintainer line at that point.

**Comment by newtmitch** [comment]
Dan - to close the loop - just updated the images on Docker hub, as well as the top-level README with the new tags. Thanks again for the help.

**Comment by danstreeter** [comment]
Hey - no worries on all of the above... Not sure why I didn't get notifications =( They are turned on on the settings... sorry I didn't respond =(

**Comment by newtmitch** [comment]
no worries on not responding. I personally ignore my email for sooo long. :)

**Pull request merged**
